### ISSUE TITLE
Execute "code_change" if exported, on module recompile.

### ISSUE THREAD

**Issue by Dryymoon** [rustyio/sync#60]
If any way to trigger some function when module/s recompiled?

**Comment by choptastic** [comment]
Hi Igor,

Sorry for the delay. You could look into using post-hooks to see if that
works for you. I haven't done anything with them myself (just merged them
in as they looked alright), but if it works for you, I'd love to hear:

https://github.com/rustyio/sync#sync-post-hooks

-Jesse

On Mon, Jun 22, 2015 at 12:16 PM, Igor Pilipenko <notifications@github.com>
wrote:

> If any way to trigger some function when module/s recompiled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rustyio/sync/issues/60>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
