### ISSUE TITLE
how to stop sync recompile erlang source？

### ISSUE THREAD

**Issue by chenshaobo** [rustyio/sync#64]
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:151: Warning: variable 'M' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:157: Warning: variable 'Count' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:159: Warning: variable 'Count' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:159: Warning: variable 'Node' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:164: Warning: variable 'Other' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:185: Warning: variable 'NodeNum' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:185: Warning: variable 'Pid' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:225: Warning: variable 'Count' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:225: Warning: variable 'Node' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:0: Recompiled with 1 warnings
10:02:59.974 [error] /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:52: Warning: variable 'Pid1a' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:53: Warning: variable 'Pid1b' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:54: Warning: variable 'Pid1c' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:116: Warning: variable 'N' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:0: Recompiled with 1 warnings
10:03:00.086 [error] /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:34: Warning: variable 'Config' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:57: Warning: variable 'Ch' is unused
/mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:0: Recompiled with 1 warnings

as above ,when system start,sync will start to recompile the  erlang lib .

**Comment by choptastic** [comment]
Weird. It's definitely not supposed to do that, and I certainly don't
experience that. I'm not sure what could be causing it to recompile the
erlang libs.

It's supposed to ignore system modules here (
https://github.com/rustyio/sync/blob/master/src/sync_scanner.erl#L136), but
if the code path includes the base erlang system, I don't know how it'll
act.

What kind of environment is this using? Is this a reltool or relx release?
What is the code path and lib_paths set to for this application?



On Tue, Dec 1, 2015 at 8:04 PM, chenshaobo <notifications@github.com> wrote:

> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:151:
> Warning: variable 'M' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:157:
> Warning: variable 'Count' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:159:
> Warning: variable 'Count' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:159:
> Warning: variable 'Node' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:164:
> Warning: variable 'Other' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:185:
> Warning: variable 'NodeNum' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:185:
> Warning: variable 'Pid' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:225:
> Warning: variable 'Count' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:225:
> Warning: variable 'Node' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/distr_startup_SUITE.erl:0:
> Recompiled with 1 warnings
> 10:02:59.974 [error]
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:52:
> Warning: variable 'Pid1a' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:53:
> Warning: variable 'Pid1b' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:54:
> Warning: variable 'Pid1c' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:116:
> Warning: variable 'N' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/mnesia_power_SUITE.erl:0:
> Recompiled with 1 warnings
> 10:03:00.086 [error]
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:34:
> Warning: variable 'Config' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:57:
> Warning: variable 'Ch' is unused
> /mnt/hgfs/workspace/software/otp_src_R16B03-1/lib/test_server/src/things/random_kill_SUITE.erl:0:
> Recompiled with 1 warnings
>
> as above ,when system start,sync will start to recompile the erlang lib .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rustyio/sync/issues/64>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
