### ISSUE TITLE
Using macos notification api instead of growl

### ISSUE THREAD

**Issue by TangMonk** [rustyio/sync#74]
https://developer.apple.com/notifications/

```
osascript -e 'display notification "Lorem ipsum dolor sit amet" with title "Title"'
```

**Comment by choptastic** [comment]
Hi, it was undocumented, but you can use the OSX Notifcation system by specifying

`{executable, notification_center}` in your sync config. The default value is `{executable, auto}`

**Comment by choptastic** [comment]
https://github.com/rustyio/sync#troubleshooting-growl-notifications

**Comment by TangMonk** [comment]
thanks!
