### ISSUE TITLE
What is the open source protocol for this library?Can I use it freely in my company's test products without open source?

### ISSUE THREAD

**Issue by feihongmeilian** [rustyio/sync#84]
As  title，Thanks！ @rustyio

**Comment by choptastic** [comment]
It's MIT licensed. Apparently Rusty never put the LICENSE file in the root directory. Thanks for pointing that out.

**Comment by choptastic** [comment]
To expound on that, yes, you can include it in your closed source projects, but please include attribution.

**Comment by feihongmeilian** [comment]
Ok, thanks very much for your reply！
