### ISSUE TITLE
Sync:go() is failing to located .hrl files in the include/ directory

### ISSUE THREAD

**Issue by dotsiadia** [rustyio/sync#85]
On some nitrogren installations it is working fine but others it has completely failed to locate the .hrl files in the include directory!

**Comment by choptastic** [comment]
Interesting. What version of Erlang?

**Comment by dotsiadia** [comment]
Erlang/OTP 19

**Comment by vasu-dasari** [comment]
@dotsiadia Can you try the `sync` from [vasu-dasari/sync](https://github.com/vasu-dasari/sync). I tried to address directory discovery issues with this commit. Also I raised a PR some time back with these changes.

**Comment by dotsiadia** [comment]
@vasu-dasari When I use [vasu-darari/sync](https://github.com/vasu-dasari/sync) and run **sync:go()** this is the error I get.

=ERROR REPORT==== 3-Dec-2018::12:21:08 ===
myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:7: Error: can't find include file "compat.hrl"
myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:148: Error: undefined macro 'HASH/1'
myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:153: Error: function hash_body/1 undefined

**Comment by choptastic** [comment]
I've merged the commit from @vasu-dasari as well as added a few things myself, hopefully this helps.

@dotsiadia: Try this:

1) Blow away all the .beam files in ebin and your lib/*/ebin directories.

2) Copy the updated rebar file from: https://github.com/nitrogen/nitrogen/blob/master/rebar (this rebar was built from master at https://github.com/choptastic/rebar), if you want to review the code.

3) Then re-run `make`.  *Hopefully* it should all be good.

Let us know how it goes!

**Comment by dotsiadia** [comment]
@vasu-dasari @choptastic Here is the rebar.conf file

    {sub_dirs, [ "site",  "deps" ]}.
    {cover_enabled, true}.
    {erl_opts, [debug_info, fail_on_warning]}.
    {deps_dir, ["lib"]}.
    {deps, [    
       {cowboy,        {git, "git://github.com/ninenines/cowboy",         {tag, "2.4.0"}}},
       %% Uncomment the following lines and comment the bottom lines with specific
       %% tags to always pull the latest versions
       {simple_bridge, {git, "git://github.com/nitrogen/simple_bridge",  {branch, master}}},
       {nprocreg,      {git, "git://github.com/nitrogen/nprocreg",     {branch, master}}},
       {nitrogen_core, {git, "git://github.com/nitrogen/nitrogen_core",{branch, master}}},
       %{sync,          {git, "git://github.com/rustyio/sync",            {branch, master}}},
       {sync,     {git, "https://github.com/vasu-dasari/sync",   {branch, master}}},
       {simple_cache,  {git, "git://github.com/nitrogen/simple_cache",   {branch, master}}}
    ]}
I've tried out both suggestions, these errors below have not appeared again

    =ERROR REPORT==== 3-Dec-2018::12:21:08 ===
    myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:7: Error: can't find include file "compat.hrl"
    myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:148: Error: undefined macro 'HASH/1'
    myapp/lib/simple_bridge/src/webmachine_bridge_modules/webmachine_simple_bridge_static.erl:153: Error: function hash_body/1 undefined

But still the .hrl files in the include/ can't be found error persists

    myapp/site/src/modx.erl:3: Error: can't find include file "headfile.hrl"

**Comment by choptastic** [comment]
Hmm.. Trying using sync from https://github.com/rustyio/sync (this includes all the updates from @vasu-dasari as well as myself.

And to be sure, your headfile.hrl is in `myapp/site/include/headfile.hrl`, correct?

**Comment by dotsiadia** [comment]
@choptastic @vasu-dasari sync now work fine after restoring to [https://github.com/rustyio/sync](https://github.com/rustyio/sync)

**Comment by vasu-dasari** [comment]
@dotsiadia Glad it worked out.
