### ISSUE TITLE
Does Sync have a license?

### ISSUE THREAD

**Issue by zkessin** [rustyio/sync#86]
Hex.pm says MIT but I don't see any license here, can someone clarify

**Comment by choptastic** [comment]
It is MIT Licensed, but we should add a LICENCE file.  The only reference to MIT is at the top of sync.erl here: https://github.com/rustyio/sync/blob/master/src/sync.erl#L3

**Comment by zkessin** [comment]
Thanks, adding a licence file would be a good thing
