### ISSUE TITLE
Sync fails to pop success / warning / failure notifications onto my Ubuntu 18.04.3 desktop

### ISSUE THREAD

**Issue by Lgm-Fred** [rustyio/sync#88]
Am using sync in [nitrogen](https://github.com/nitrogen/nitrogen) with OTP 19, it works well but am failing to get desktop notifications and I have to go to the console each-time to see success / warning / failure notifications. I've the latest version of `libnotify4` and I can send custom notifications from the terminal to the desktop such as `notify-send "Error!"` and it works just fine.  Even tried out [Troubleshooting Growl Notifications](https://github.com/rustyio/sync#troubleshooting-growl-notifications) all in vain. Here's my `sync.config` file.
```
[
    {sync,[

        %% growl: Desktop notifications
        %% valid values: all | none | [success | warning | error]
        %% default: all
        {growl, all},

        %% log: Console notifications
        %% valid values: all | none | [success | warnings | errors]
        %% default: all
        {log, all},

        %% non_descendant: How to handle beams whose original source path is
        %% not a descendant of the current working directory.
        %%
        %% valid values: fix | allow | ignore
        %% * fix = attempt to find source files under current directory
        %% * allow = don't do anything special, use the non-descendant path and
        %%   watch that file
        %% * ignore = don't watch that module at all and ignore any changes to
        %%   its source path
        %% default: fix
        {non_descendant, fix},

        %% excluded_modules: Ignore any modules listed
        %% default: []
        {excluded_modules, []},

        %% executable: Identify the program that you want run by the "growl" notifications
        %% valid values: auto | notifu | 'notify-send' | growlnotify | emacsclient
        %% * auto = allow sync to autodetect which program to run
        %% * growlnotify = Use Growl for Mac
        %% * 'notify-send' = Use libnotify for Linux
        %% * notifu = The notifu program for Windows
        %% * emacsclient = Emacs notifications
        %% default: auto
        {executable, 'notify-send'}
    ]}
].
```

**Comment by choptastic** [comment]
Hi @Lgm-Fred 

Very odd indeed!   I'm not sure I know the easy answer to this - I also run Ubuntu 18.04 (technically, I'm running Xubuntu, but should be the same).

To troubleshoot this, I'd make the following change:

Just before the `os:cmd` call here, https://github.com/rustyio/sync/blob/master/src/sync_notify.erl#L72

Throw in the following line:

`error_logger:info_msg("Running: ~s~n", [Cmd]).`

This will construct the exact command line that it's trying to run, then you should be able to copy and paste it to see if perhaps there's something there that libnotify doesn't like.

If you do that, please let me know what you come up with.

**Comment by Lgm-Fred** [comment]
Hi @choptastic 

I just added the `error_logger:info_msg("Running: ~s~n", [Cmd])` line and this is what I get on the console after making changes to a module.
```
=INFO REPORT==== 9-Feb-2020::06:53:38 ===
/home/lgm/web_apps/nnote/site/src/nnote_get.erl:0: Recompiled.

=INFO REPORT==== 9-Feb-2020::06:54:05 ===
/home/lgm/web_apps/nnote/site/src/nnote_get.erl:0: Recompiled.

=INFO REPORT==== 9-Feb-2020::06:54:05 ===
nnote_get: Reloaded! (Beam changed.)

=INFO REPORT==== 9-Feb-2020::06:54:05 ===
Running: notify-send -i "/home/lgm/web_apps/nnote/lib/sync/ebin/../icons/success.png" "Success!" "Reloaded nnote_get." --expire-time=5000
```
When I run the `notify-send -i "/home/lgm/web_apps/nnote/lib/sync/ebin/../icons/success.png" "Success!" "Reloaded nnote_get." --expire-time=5000` directly on the terminal sync does smile at me very well. However, it just cannot popup on its own.

**Comment by choptastic** [comment]
Hi @Lgm-Fred 

Thanks for the update  Honestly, I'm not sure.

Another thing we could try would be to capture the results of the `os:cmd` call.

```
Res = os:cmd(Cmd),
error_logger:info_msg("Return from oscmd: ~p",[Res]).
```

That will at least give you some insight into what's happening when Erlang tries calling `notify-send`.

**Comment by Lgm-Fred** [comment]
Hello @choptastic 

I appreciate your effort, Am kinda a newbie in the Erlang world.
[`Cmd`](https://github.com/rustyio/sync/blob/9106be75883d7646dae72d4ac80c6ea88464a5ca/src/sync_notify.erl#L58) & [`Cmd2`](https://github.com/rustyio/sync/blob/9106be75883d7646dae72d4ac80c6ea88464a5ca/src/sync_notify.erl#L71) return pretty-much the same thing whereas [`Res = os:cmd(Cmd2)`](https://github.com/rustyio/sync/blob/9106be75883d7646dae72d4ac80c6ea88464a5ca/src/sync_notify.erl#L72) returns an empty list.

```
=INFO REPORT==== 14-Feb-2020::14:38:57 ===
index: Reloaded! (Beam changed.)

=INFO REPORT==== 14-Feb-2020::14:38:57 ===
Running(Cmd): notify-send -i "/home/lgm/web_apps/dotAfya/lib/sync/ebin/../icons/success.png" "Success!" "Reloaded index." --expire-time=5000

=INFO REPORT==== 14-Feb-2020::14:38:57 ===
Running(Cmd2): notify-send -i "/home/lgm/web_apps/dotAfya/lib/sync/ebin/../icons/success.png" "Success!" "Reloaded index." --expire-time=5000

=INFO REPORT==== 14-Feb-2020::14:38:57 ===
Return from oscmd: []

```

**Comment by Lgm-Fred** [comment]
Hello @choptastic

I've come to realise that when I run `notify-send` directly from the terminal as a normal user it is all fine but it doesn't work when run with superuser privileges. I have been running my nitrogen as `sudo ./bin/nitrogen <argument>` and that was why [sync](https://github.com/rustyio/sync) wasn't smiling at me yet working fine on the console.
I can now work fine except that the only way to run nitrogen is `./bin/nitrogen console`, the `./bin/nitrogen start` option doesn't work for me now since when I try to attach I get 

```
=ERROR REPORT==== 7-Apr-2020::08:58:10 ===
Error when reading /home/ayiko/.erlang.cookie: eaccesescript: exception error: no match of right hand side value 
                 {error,
                     {{shutdown,
                          {failed_to_start_child,auth,
                              {"Error when reading /home/ayiko/.erlang.cookie: eacces",
                               [{auth,init_cookie,0,
                                    [{file,"auth.erl"},{line,286}]},
                                {auth,init,1,[{file,"auth.erl"},{line,140}]},
                                {gen_server,init_it,6,
                                    [{file,"gen_server.erl"},{line,328}]},
                                {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,247}]}]}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['afyaCom_maint_7156@127.0.0.1',longnames],
                               false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
```
And now I have to kill the erlang process running before I can successfully run `./bin/nitrogen console` again. Everything else works fine with superuser privileges except [sync ](https://github.com/rustyio/sync)smiling at me.

Thanks for the help.

**Comment by choptastic** [comment]
Hi @Lgm-Fred , so glad you figured it out.

I would generally recommend not running Nitrogen with root privileges.  Are you running as root to bind to port 80?  If so, you can get around this using `setcap`.  Something like:

setcap 'cap_net_bind_service=+ep' /path/to/beam.smp`.

If your setup is anything like mine, it's in /usr/lib/erlang/erts-X.Y.Z/bin/beam.smp`


It sounds like because you were running as root, the file `/home/ayiko/.erlang.cookie` was autogenerated with root.  You could try doing `sudo chown ayiko:ayiko /home/ayiko/.erlang.cookie` and that should change the ownership of that file to you.

**Comment by Lgm-Fred** [comment]
Perfect! Things are now back to normal. Thanks a lot for the help @choptastic
